Added ScaleAutonCommand
Team694/Wildcard pull request #23
Opened 2018-01-27 19:16 UTC by PrathamRawat

2018-01-27 19:27 UTC, huiminwu requested changes
Add logic to get FMS data to a GameData.java file in the util package to avoid redundancies. Refer to PoC FMS branch f 2018-proof-of-concepts.

2018-01-30 22:20 UTC, adrisj7 commented on src/org/usfirst/frc/team694/robot/commands/auton/DrivetrainMoveToLineCommand.java
> +        return isReached || (Math.max(Robot.drivetrain.getRightEncoderDistance(),Robot.drivetrain.getLeftEncoderDistance()) > (distance));
Use Robot.drivetrain.getEncoderDistance() which grabs the max of both sides for you

2018-01-30 22:22 UTC, adrisj7 commented on src/org/usfirst/frc/team694/robot/commands/auton/DrivetrainMoveToLineCommand.java
> +    private double speedNumber = 0;// 0,1, or 2, repesents speeds 0.25,0.5,0.75 respectively.
Do not use this. You're literally converting a speed into an imaginary "speed number" unit and then converting it back to a speed when you use it, which makes it pointless. Just use the raw speed value, don't convert it or anything.

2018-01-30 22:23 UTC, adrisj7 commented on src/org/usfirst/frc/team694/robot/commands/auton/SameSideRightAngleAutonCommand.java
> +public class SameSideRightAngleAutonCommand extends CommandGroup {
Don't add this file if there's nothing in it

2018-01-30 22:24 UTC, TacoTechnica requested changes
Fix DrivetrainMoveToLineCommand
Remove or populate empty SameSideRightAngleAutonCommand

2018-02-03 15:13 UTC, closed without merging