Update the Field Map and Auton Scale to work with the interface.
Team694/Wildcard pull request #44
Opened 2018-02-08 01:05 UTC by plau10

2018-02-08 03:46 UTC, huiminwu requested changes
Fix merge conflicts and do not push classpath.

2018-02-09 22:02 UTC, plau10 commented
Fixed the merge conflicts

2018-02-10 15:56 UTC, TacoTechnica approved these changes
Looks mostly good, we'll fix this while doing the println robot

2018-02-10 16:39 UTC, huiminwu approved these changes

2018-02-12 16:33 UTC, merged